services:
  - type: web
    name: sistema-control
    env: python
    buildCommand: |
      pip install -r requirements.txt
      bash render-build.sh
    startCommand: gunicorn sistema_control.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: sistema_control.settings
